version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ur root password
      MYSQL_DATABASE: leads_db
    ports:
      - "3307:3306"

  fastapi_app:
    build: .
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_ACCOUNT_SSID: ${TWILIO_ACCOUNT_SSID}
      TWILIO_NUMBER: ${TWILIO_NUMBER}
      DATABASE_URL: ${DATABASE_URL}
